using System.Globalization;
using IMS_Mobile.MVVM.Models;

namespace IMS_Mobile.Converters
{
    public class CurrencyConverter : IValueConverter
    {
        public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (value is Currency currency)
            {
                return currency switch
                {
                    Currency.USD => "💵 USD - US Dollar",
                    Currency.EUR => "💶 EUR - Euro",
                    Currency.GBP => "💷 GBP - British Pound",
                    Currency.JPY => "💴 JPY - Japanese Yen",
                    Currency.LBP => "🇱🇧 LBP - Lebanese Pound",
                    Currency.CAD => "🇨🇦 CAD - Canadian Dollar",
                    Currency.AUD => "🇦🇺 AUD - Australian Dollar",
                    Currency.CHF => "🇨🇭 CHF - Swiss Franc",
                    Currency.CNY => "🇨🇳 CNY - Chinese Yuan",
                    Currency.SEK => "🇸🇪 SEK - Swedish Krona",
                    Currency.NOK => "🇳🇴 NOK - Norwegian Krone",
                    Currency.DKK => "🇩🇰 DKK - Danish Krone",
                    Currency.PLN => "🇵🇱 PLN - Polish Zloty",
                    Currency.CZK => "🇨🇿 CZK - Czech Koruna",
                    Currency.HUF => "🇭🇺 HUF - Hungarian Forint",
                    Currency.RON => "🇷🇴 RON - Romanian Leu",
                    Currency.BGN => "🇧🇬 BGN - Bulgarian Lev",
                    Currency.HRK => "🇭🇷 HRK - Croatian Kuna",
                    Currency.RSD => "🇷🇸 RSD - Serbian Dinar",
                    Currency.MKD => "🇲🇰 MKD - Macedonian Denar",
                    Currency.BAM => "🇧🇦 BAM - Bosnia and Herzegovina Mark",
                    Currency.ALL => "🇦🇱 ALL - Albanian Lek",
                    Currency.MNT => "🇲🇳 MNT - Mongolian Tugrik",
                    Currency.KRW => "🇰🇷 KRW - South Korean Won",
                    Currency.SGD => "🇸🇬 SGD - Singapore Dollar",
                    Currency.HKD => "🇭🇰 HKD - Hong Kong Dollar",
                    Currency.TWD => "🇹🇼 TWD - Taiwan Dollar",
                    Currency.THB => "🇹🇭 THB - Thai Baht",
                    Currency.MYR => "🇲🇾 MYR - Malaysian Ringgit",
                    Currency.IDR => "🇮🇩 IDR - Indonesian Rupiah",
                    Currency.PHP => "🇵🇭 PHP - Philippine Peso",
                    Currency.VND => "🇻🇳 VND - Vietnamese Dong",
                    Currency.INR => "🇮🇳 INR - Indian Rupee",
                    Currency.PKR => "🇵🇰 PKR - Pakistani Rupee",
                    Currency.BDT => "🇧🇩 BDT - Bangladeshi Taka",
                    Currency.LKR => "🇱🇰 LKR - Sri Lankan Rupee",
                    Currency.NPR => "🇳🇵 NPR - Nepalese Rupee",
                    Currency.AFN => "🇦🇫 AFN - Afghan Afghani",
                    Currency.IRR => "🇮🇷 IRR - Iranian Rial",
                    Currency.IQD => "🇮🇶 IQD - Iraqi Dinar",
                    Currency.JOD => "🇯🇴 JOD - Jordanian Dinar",
                    Currency.KWD => "🇰🇼 KWD - Kuwaiti Dinar",
                    Currency.BHD => "🇧🇭 BHD - Bahraini Dinar",
                    Currency.QAR => "🇶🇦 QAR - Qatari Riyal",
                    Currency.AED => "🇦🇪 AED - UAE Dirham",
                    Currency.OMR => "🇴🇲 OMR - Omani Rial",
                    Currency.SAR => "🇸🇦 SAR - Saudi Riyal",
                    Currency.YER => "🇾🇪 YER - Yemeni Rial",
                    Currency.EGP => "🇪🇬 EGP - Egyptian Pound",
                    Currency.MAD => "🇲🇦 MAD - Moroccan Dirham",
                    Currency.TND => "🇹🇳 TND - Tunisian Dinar",
                    Currency.DZD => "🇩🇿 DZD - Algerian Dinar",
                    Currency.LYD => "🇱🇾 LYD - Libyan Dinar",
                    Currency.SDG => "🇸🇩 SDG - Sudanese Pound",
                    Currency.ETB => "🇪🇹 ETB - Ethiopian Birr",
                    Currency.KES => "🇰🇪 KES - Kenyan Shilling",
                    Currency.UGX => "🇺🇬 UGX - Ugandan Shilling",
                    Currency.TZS => "🇹🇿 TZS - Tanzanian Shilling",
                    Currency.ZAR => "🇿🇦 ZAR - South African Rand",
                    Currency.NGN => "🇳🇬 NGN - Nigerian Naira",
                    Currency.GHS => "🇬🇭 GHS - Ghanaian Cedi",
                    Currency.XOF => "🇸🇳 XOF - West African CFA Franc",
                    Currency.XAF => "🇨🇲 XAF - Central African CFA Franc",
                    Currency.BRL => "🇧🇷 BRL - Brazilian Real",
                    Currency.ARS => "🇦🇷 ARS - Argentine Peso",
                    Currency.CLP => "🇨🇱 CLP - Chilean Peso",
                    Currency.COP => "🇨🇴 COP - Colombian Peso",
                    Currency.MXN => "🇲🇽 MXN - Mexican Peso",
                    Currency.PEN => "🇵🇪 PEN - Peruvian Sol",
                    Currency.UYU => "🇺🇾 UYU - Uruguayan Peso",
                    Currency.VES => "🇻🇪 VES - Venezuelan Bolivar",
                    Currency.RUB => "🇷🇺 RUB - Russian Ruble",
                    Currency.UAH => "🇺🇦 UAH - Ukrainian Hryvnia",
                    Currency.BYN => "🇧🇾 BYN - Belarusian Ruble",
                    Currency.KZT => "🇰🇿 KZT - Kazakhstani Tenge",
                    Currency.UZS => "🇺🇿 UZS - Uzbekistani Som",
                    Currency.KGS => "🇰🇬 KGS - Kyrgyzstani Som",
                    Currency.TJS => "🇹🇯 TJS - Tajikistani Somoni",
                    Currency.TMT => "🇹🇲 TMT - Turkmenistani Manat",
                    Currency.AZN => "🇦🇿 AZN - Azerbaijani Manat",
                    Currency.AMD => "🇦🇲 AMD - Armenian Dram",
                    Currency.GEL => "🇬🇪 GEL - Georgian Lari",
                    Currency.TRY => "🇹🇷 TRY - Turkish Lira",
                    Currency.JMD => "🇯🇲 JMD - Jamaican Dollar",
                    Currency.BBD => "🇧🇧 BBD - Barbadian Dollar",
                    Currency.BZD => "🇧🇿 BZD - Belize Dollar",
                    Currency.XCD => "🇦🇬 XCD - East Caribbean Dollar",
                    Currency.TTD => "🇹🇹 TTD - Trinidad and Tobago Dollar",
                    Currency.GYD => "🇬🇾 GYD - Guyanese Dollar",
                    Currency.SRD => "🇸🇷 SRD - Surinamese Dollar",
                    Currency.FKP => "🇫🇰 FKP - Falkland Islands Pound",
                    Currency.NZD => "🇳🇿 NZD - New Zealand Dollar",
                    Currency.FJD => "🇫🇯 FJD - Fijian Dollar",
                    Currency.PGK => "🇵🇬 PGK - Papua New Guinean Kina",
                    Currency.SBD => "🇸🇧 SBD - Solomon Islands Dollar",
                    Currency.VUV => "🇻🇺 VUV - Vanuatu Vatu",
                    Currency.WST => "🇼🇸 WST - Samoan Tala",
                    Currency.TOP => "🇹🇴 TOP - Tongan Pa'anga",
                    Currency.XPF => "🇵🇫 XPF - CFP Franc",
                    _ => "💵 USD - US Dollar"
                };
            }
            return "💵 USD - US Dollar";
        }

        public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (value is string currencyString)
            {
                return currencyString switch
                {
                    "💵 USD - US Dollar" => Currency.USD,
                    "💶 EUR - Euro" => Currency.EUR,
                    "💷 GBP - British Pound" => Currency.GBP,
                    "💴 JPY - Japanese Yen" => Currency.JPY,
                    "🇱🇧 LBP - Lebanese Pound" => Currency.LBP,
                    "🇨🇦 CAD - Canadian Dollar" => Currency.CAD,
                    "🇦🇺 AUD - Australian Dollar" => Currency.AUD,
                    "🇨🇭 CHF - Swiss Franc" => Currency.CHF,
                    "🇨🇳 CNY - Chinese Yuan" => Currency.CNY,
                    "🇸🇪 SEK - Swedish Krona" => Currency.SEK,
                    "🇳🇴 NOK - Norwegian Krone" => Currency.NOK,
                    "🇩🇰 DKK - Danish Krone" => Currency.DKK,
                    "🇵🇱 PLN - Polish Zloty" => Currency.PLN,
                    "🇨🇿 CZK - Czech Koruna" => Currency.CZK,
                    "🇭🇺 HUF - Hungarian Forint" => Currency.HUF,
                    "🇷🇴 RON - Romanian Leu" => Currency.RON,
                    "🇧🇬 BGN - Bulgarian Lev" => Currency.BGN,
                    "🇭🇷 HRK - Croatian Kuna" => Currency.HRK,
                    "🇷🇸 RSD - Serbian Dinar" => Currency.RSD,
                    "🇲🇰 MKD - Macedonian Denar" => Currency.MKD,
                    "🇧🇦 BAM - Bosnia and Herzegovina Mark" => Currency.BAM,
                    "🇦🇱 ALL - Albanian Lek" => Currency.ALL,
                    "🇲🇳 MNT - Mongolian Tugrik" => Currency.MNT,
                    "🇰🇷 KRW - South Korean Won" => Currency.KRW,
                    "🇸🇬 SGD - Singapore Dollar" => Currency.SGD,
                    "🇭🇰 HKD - Hong Kong Dollar" => Currency.HKD,
                    "🇹🇼 TWD - Taiwan Dollar" => Currency.TWD,
                    "🇹🇭 THB - Thai Baht" => Currency.THB,
                    "🇲🇾 MYR - Malaysian Ringgit" => Currency.MYR,
                    "🇮🇩 IDR - Indonesian Rupiah" => Currency.IDR,
                    "🇵🇭 PHP - Philippine Peso" => Currency.PHP,
                    "🇻🇳 VND - Vietnamese Dong" => Currency.VND,
                    "🇮🇳 INR - Indian Rupee" => Currency.INR,
                    "🇵🇰 PKR - Pakistani Rupee" => Currency.PKR,
                    "🇧🇩 BDT - Bangladeshi Taka" => Currency.BDT,
                    "🇱🇰 LKR - Sri Lankan Rupee" => Currency.LKR,
                    "🇳🇵 NPR - Nepalese Rupee" => Currency.NPR,
                    "🇦🇫 AFN - Afghan Afghani" => Currency.AFN,
                    "🇮🇷 IRR - Iranian Rial" => Currency.IRR,
                    "🇮🇶 IQD - Iraqi Dinar" => Currency.IQD,
                    "🇯🇴 JOD - Jordanian Dinar" => Currency.JOD,
                    "🇰🇼 KWD - Kuwaiti Dinar" => Currency.KWD,
                    "🇧🇭 BHD - Bahraini Dinar" => Currency.BHD,
                    "🇶🇦 QAR - Qatari Riyal" => Currency.QAR,
                    "🇦🇪 AED - UAE Dirham" => Currency.AED,
                    "🇴🇲 OMR - Omani Rial" => Currency.OMR,
                    "🇸🇦 SAR - Saudi Riyal" => Currency.SAR,
                    "🇾🇪 YER - Yemeni Rial" => Currency.YER,
                    "🇪🇬 EGP - Egyptian Pound" => Currency.EGP,
                    "🇲🇦 MAD - Moroccan Dirham" => Currency.MAD,
                    "🇹🇳 TND - Tunisian Dinar" => Currency.TND,
                    "🇩🇿 DZD - Algerian Dinar" => Currency.DZD,
                    "🇱🇾 LYD - Libyan Dinar" => Currency.LYD,
                    "🇸🇩 SDG - Sudanese Pound" => Currency.SDG,
                    "🇪🇹 ETB - Ethiopian Birr" => Currency.ETB,
                    "🇰🇪 KES - Kenyan Shilling" => Currency.KES,
                    "🇺🇬 UGX - Ugandan Shilling" => Currency.UGX,
                    "🇹🇿 TZS - Tanzanian Shilling" => Currency.TZS,
                    "🇿🇦 ZAR - South African Rand" => Currency.ZAR,
                    "🇳🇬 NGN - Nigerian Naira" => Currency.NGN,
                    "🇬🇭 GHS - Ghanaian Cedi" => Currency.GHS,
                    "🇸🇳 XOF - West African CFA Franc" => Currency.XOF,
                    "🇨🇲 XAF - Central African CFA Franc" => Currency.XAF,
                    "🇧🇷 BRL - Brazilian Real" => Currency.BRL,
                    "🇦🇷 ARS - Argentine Peso" => Currency.ARS,
                    "🇨🇱 CLP - Chilean Peso" => Currency.CLP,
                    "🇨🇴 COP - Colombian Peso" => Currency.COP,
                    "🇲🇽 MXN - Mexican Peso" => Currency.MXN,
                    "🇵🇪 PEN - Peruvian Sol" => Currency.PEN,
                    "🇺🇾 UYU - Uruguayan Peso" => Currency.UYU,
                    "🇻🇪 VES - Venezuelan Bolivar" => Currency.VES,
                    "🇷🇺 RUB - Russian Ruble" => Currency.RUB,
                    "🇺🇦 UAH - Ukrainian Hryvnia" => Currency.UAH,
                    "🇧🇾 BYN - Belarusian Ruble" => Currency.BYN,
                    "🇰🇿 KZT - Kazakhstani Tenge" => Currency.KZT,
                    "🇺🇿 UZS - Uzbekistani Som" => Currency.UZS,
                    "🇰🇬 KGS - Kyrgyzstani Som" => Currency.KGS,
                    "🇹🇯 TJS - Tajikistani Somoni" => Currency.TJS,
                    "🇹🇲 TMT - Turkmenistani Manat" => Currency.TMT,
                    "🇦🇿 AZN - Azerbaijani Manat" => Currency.AZN,
                    "🇦🇲 AMD - Armenian Dram" => Currency.AMD,
                    "🇬🇪 GEL - Georgian Lari" => Currency.GEL,
                    "🇹🇷 TRY - Turkish Lira" => Currency.TRY,
                    "🇯🇲 JMD - Jamaican Dollar" => Currency.JMD,
                    "🇧🇧 BBD - Barbadian Dollar" => Currency.BBD,
                    "🇧🇿 BZD - Belize Dollar" => Currency.BZD,
                    "🇦🇬 XCD - East Caribbean Dollar" => Currency.XCD,
                    "🇹🇹 TTD - Trinidad and Tobago Dollar" => Currency.TTD,
                    "🇬🇾 GYD - Guyanese Dollar" => Currency.GYD,
                    "🇸🇷 SRD - Surinamese Dollar" => Currency.SRD,
                    "🇫🇰 FKP - Falkland Islands Pound" => Currency.FKP,
                    "🇳🇿 NZD - New Zealand Dollar" => Currency.NZD,
                    "🇫🇯 FJD - Fijian Dollar" => Currency.FJD,
                    "🇵🇬 PGK - Papua New Guinean Kina" => Currency.PGK,
                    "🇸🇧 SBD - Solomon Islands Dollar" => Currency.SBD,
                    "🇻🇺 VUV - Vanuatu Vatu" => Currency.VUV,
                    "🇼🇸 WST - Samoan Tala" => Currency.WST,
                    "🇹🇴 TOP - Tongan Pa'anga" => Currency.TOP,
                    "🇵🇫 XPF - CFP Franc" => Currency.XPF,
                    _ => Currency.USD
                };
            }
            return Currency.USD;
        }
    }
}
